name: Run test
run-name: ${{ github.actor }} trigger tests in GitHub Actions
on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-flake8-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements/*_requirements.txt'
      - run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/flake8_requirements.txt
      - name: Run linter
        run: flake8

  setup-application:
    needs: run-flake8-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements/*_requirements.txt'
      - run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/common_requirements.txt
      - name: Start application
        uses: BerniWittmann/background-server-action@v1
        with:
          start: python -m uvicorn main:app
          wait-on: 'http://localhost:8000'
      - run: pip install -r ./requirements/tests_requirements.txt
      - name: Test application
        run: python -m pytest
