name: run-tests
run-name: Run tests in GitHub Actions
on: [push]
jobs:
  setup-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start application
        run: uvicorn main:app
      - name: Test application
        run: pytest
